repos:
- repo: https://github.com/hukkin/mdformat
  rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # frozen: 1.0.0
  hooks:
  - id: mdformat
    args: [--number, --wrap, '120']
    additional_dependencies:
    - mdformat-gfm
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix, --indent=2]
  - id: trailing-whitespace
- repo: https://github.com/rhysd/actionlint
  rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
  hooks:
  - id: actionlint
    additional_dependencies:
    - github.com/wasilibs/go-shellcheck/cmd/shellcheck@latest
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.30.0
  hooks:
  - id: zizmor
    args: [--no-progress, --fix]
